### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by antonkulaga** [snowkylin/rnn-handwriting-generation#3]
```
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    import model as m
  File "/home/antonkulaga/rnn-handwriting-generation/model.py", line 3, in <module>
    from utils import vectorization
  File "/home/antonkulaga/rnn-handwriting-generation/utils.py", line 261
    print "error in " + filename
                    ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by ctrlcctrlv** [comment]
Use Python 2.
